spring.application.name=noticore-api-prod

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
spring.datasource.driver-class-name=org.postgresql.Driver

# Brevo
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_SMTP_USERNAME}
spring.mail.password=${BREVO_SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
brevo.api.key=${BREVO_API_KEY}
brevo.webhook.username=${BREVO_WEBHOOK_USERNAME:}
brevo.webhook.password=${BREVO_WEBHOOK_PASSWORD:}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

#hikari configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=4
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

#liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:changelog-master.xml

#rapidapi configuration
rapidapi.proxy.secret=${RAPIDAPI_PROXY_SECRET}