spring.application.name=noticore-api

#port decalration
server.port=8080

#database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/noticore
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.open-in-view=false

#hikari configuration
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=4
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000

#liquibase configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:changelog-master.xml

#amazon SES configuration
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.region=ap-south-1